image explosao:
    pause 0.2
    "images/animation/explosion/explosion-17.png"
    0.1
    "images/animation/explosion/explosion-16.png"
    0.1
    "images/animation/explosion/explosion-15.png"
    0.1
    "images/animation/explosion/explosion-14.png"
    0.1
    "images/animation/explosion/explosion-13.png"
    0.1
    "images/animation/explosion/explosion-12.png"
    0.1
    "images/animation/explosion/explosion-11.png"
    0.1
    "images/animation/explosion/explosion-10.png"
    0.1
    "images/animation/explosion/explosion-9.png"
    0.1
    "images/animation/explosion/explosion-8.png"
    0.1
    "images/animation/explosion/explosion-7.png"
    0.1
    "images/animation/explosion/explosion-6.png"
    0.1
    "images/animation/explosion/explosion-5.png"
    0.1
    "images/animation/explosion/explosion-4.png"
    0.1
    "images/animation/explosion/explosion-3.png"
    0.1
    "images/animation/explosion/explosion-2.png"
    0.1
    "images/animation/explosion/explosion-1.png"
    0.1